import { Rubik } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Template from "./template";

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
});

export const fonts = {
  rubik,
};
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={fonts.rubik.variable}
        // className={inter.className}
      >
        <Providers>
          <Template>{children}</Template>
        </Providers>
      </body>
    </html>
  );
}
